### ISSUE TITLE
Write lesson: Math mode

### ISSUE THREAD

**Issue by josephwright** [learnlatex/learnlatex.github.io#10]
Tracker issue for writing lesson 10.

**Comment by jimhefferon** [comment]
Bruoght material over from lesson 3.  May be too big.

**Comment by davidcarlisle** [comment]
possibly change the title to Mathematics, to avoid the UK/US compromise Math(s) ?

**Comment by jimhefferon** [comment]
I personally prefer $ ..$ for math but I put \( ...\) on the grounds that someone on the team had commented  that it is the way to go: https://tex.stackexchange.com/a/513/121234.  :-)
