### ISSUE TITLE
Add translations of toc-anchor-text and toc-description

### ISSUE THREAD

**Issue by PhelypeOleinik** [learnlatex/learnlatex.github.io#101]
With the design updates, all `en` lessons now have `toc-anchor-text`, `toc-description` and `description` at the top of every lesson `.md` file that needs translation.  This issue is for keeping track of the ones already added (only completed translations listed):

- [x] `pt` @PhelypeOleinik 
- [x] `vi` @joulev 
- [x] `fr` @jejust 
- [ ] `es` @fersdt @EmanuelPrima 
- [ ] `tr`
- [ ] `de`

(check your box when completed... if github allows :)

**Comment by joulev** [comment]
> With the design updates, all `en` lessons now have `toc-anchor-text`, `toc-description` and `description` at the top of every lesson `.md` file that needs translation. This issue is for keeping track of the ones already added (only completed translations listed):
> 
>     * [ ]  `pt` @PhelypeOleinik
> 
>     * [ ]  `vi` @joulev
> 
>     * [ ]  `fr` @jejust
> 
>     * [ ]  `es` @fersdt @EmanuelPrima
> 

Thanks. I will get into it asap.
> 
> (check your box when completed... if github allows :)

It doesn't though :) (at least to me).

**Comment by PhelypeOleinik** [comment]
>
> (check your box when completed... if github allows :)
>
> It doesn't though :) (at least to me).
>

I guessed as much.  Checking the boxes essentially edits the post, so
you'd need write permission in this repo.  No problem, though, just drop
a comment here so we can keep track of what's done.

**Comment by jonasjacek** [comment]
**FYI:** The `description` will be used as meta description and maybe somewhere in the front end. The `toc-*` elements will be used solely for the table of content of lessons. 

## Meta descriptions

The value must be a free-form string that describes the page. The value must be appropriate for use in a directory of pages, e.g. in a search engine. 

* Length: ~150 characters
* https://www.w3.org/TR/2011/WD-html5-author-20110809/the-meta-element.html#standard-metadata-names
* https://www.w3.org/TR/UNDERSTANDING-WCAG20/appendixC.html

**Comment by joulev** [comment]
@jonasjacek Can the `description` be written in more than one line? The current `description`s in `en` are all written in one single line even when they are longer than 80 characters, which is not consistent to me.

**Comment by jonasjacek** [comment]
@joulev if your text editor wraps lines e.g. at 80 characters, than that is not a problem. However, meta descriptions cannot contain newline (`\n`) or carriage return (`\r`) characters. These will also not be interpreted where they are used (e.g. search engine result pages). Keep it in one line is the bulletproof way to go. I'd say frontmatter is the exception to the 80 chars rule (if there is such a rule within the team). I hope this helps.

**Comment by joulev** [comment]
@jonasjacek Thanks for the information!

**Comment by jonasjacek** [comment]
Thanks for your work so far. Still missing:

- Spanish
- German
- Janpanese
- Chinese

I've added the corresponding front matter elements to these languages and applied the 'new' toc design to all languages, where this has not been done before. So, in all languages, the TOC is using the visual presentation and semantic markup which you could see in /en. 

**Tips:** For the anchor text, be short and precise, so people can easily scan (maybe not even read) the table of contents for what they are looking for. The description part should contain relevant keywords, which people might look for. Space is limited (on purpose). Brevity and catching attention are king here. It's all about making the TOC easy to digest.

If the content breaks the design, for now, that's OK. I'll adapt it later, once we are content complete.
