### ISSUE TITLE
Changes to additional lessons specific to languages and extra lesson

### ISSUE THREAD

**Issue by jonasjacek** [learnlatex/learnlatex.github.io#107]
I believe the additional lessons specific to languages (`language-01.md` and sometimes `language-02.md`) as well as the extra lesson `extra-01` in each of the language directories, should be linked or even included in on of the earlier lessons, instead of being linked from the language specific home pages, below (hidden) the table of contents.

Shouldn't the information contained in the language files be made available early? I have the feeling lesson 3 might be suitable.

The extra lesson could be part of lesson 16. Alternatively, language and extra lessons could become lessons of their own. Looking at the page tree, they are already lessons of their own, but they are not part of the table of contents, which feels odd to me:

```text
home
  - start
    - lesson
      - lesson-01
        - more-01
      - lesson-02
        - more-02
      - lesson-03
        - more-03
      - lesson-04
        - more-04
      - lesson-05
        - more-05
      - lesson-06
        - more-06
      - lesson-07
        - more-07
      - lesson-08
        - more-08
      - lesson-09
        - more-09
      - lesson-10
        - more-10
      - lesson-11
        - more-11
      - lesson-12
        - more-12
      - lesson-13
        - more-13
      - lesson-14
        - more-14
      - lesson-15
        - more-15
      - lesson-16
        - more-16
      - extra-01
      - language-01
      - language-02
    - mission
    - help
    - licenses
    - contact
```

**So I would like to ask for the following:**

- Discuss if language specifics and the extra lesson should become part of a lesson or even a lessons themselves

**The goal**

- My goal is to to keep the structure of lessons as simple as possible (so people don't have to think about it, when doing the lessons). 
- I want to make sure that, everyone who follows the lessons, automatically discovers all the information.
- I want to make sure there are actually as many lessons in the table of contents and not hidden ones on the side, which might be confusing for users.
- It will help me to streamline the design, which will help to make lessons easily discoverable (e.g. via table of contents or even URI, if you think about URIs as (early) user interfaces)

I hope this makes sense to you, too.

**Comment by josephwright** [comment]
The 'extra' or 'showcase' stuff could go into or be linked from lesson 16; the aim of adding it was to give us somewhere to highlight things that go beyond what we can cover.

**Comment by jonasjacek** [comment]
What do you think about adding the language specifics to https://learnlatex.netlify.app/en/lesson-06 - this is where the babel packages is introduced anyway.

**Comment by josephwright** [comment]
> What do you think about adding the language specifics to https://learnlatex.netlify.app/en/lesson-06 - this is where the babel packages is introduced anyway.

The idea of the 'language extras' was to avoid getting bogged down in detail too early, and also to avoid needing fundamentally different text between languages. So to me a _link_ from lesson 6 would be fine, but I'd very wary of making the entire lesson language-dependent.

**Comment by davidcarlisle** [comment]
[I thought I posted a reply to this earlier but I don't see it now?]

The lessons-xx,  language-xx, and extra-xx are really all in the same (sectioned) table of contents and linked via the "next lesson" links.  So I don't think I would  agree that they are not in the main sequence or can easily be missed?

We wanted the main initial 16 lessons translations to be more or less literal translations of the english lessons, so having the language-xx lessons at the end which are explicitly not translations, but language-specific extra lessons is a useful distinction  I think.

**Comment by jonasjacek** [comment]
Thank you both for your answers. This topic gives the UX expert in me lots of headaches. UX designer/information architect problems.

From what I see, extra-01 and languages-0* are lessons. In contents they are referred to as lessons, they are also linked as lessons (e.g. from lesson 16, languages-0* is linked in the inter-lesson links as 'Next lesson'). The inter-lesson links also show up on language-01. For me, as a front-end designer and end user, this is a clear indicator, that what I am looking at, is a lesson.

There are 16 lessons in the TOC, but in reality there are 16 and two halfs, 17 and a half or 18. This makes it difficult for users to discover/rediscover this information. I assume, that's why extra-01 and language-01 were linked from the home page. Below the regular TOC but still with a TOCish link style. That's a hack I would like to - for the sake of user experience - get rid of. I hope you can see the contradiction: applying inter-lesson links (lesson behavior), referring to them as lessons but not listing them in the list of lessons and naming them differently. 

Are extra-01 and languages-0* lessons or not?

> ... the main initial 16 lessons translations to be more or less literal translations of the english lessons ...

I understand that and it makes sense for the team to work like that. On the other hand, to the end user it should be unimportant. To end users, these are (probably) just lessons, and thus should behave like all other lessons. Internal workings should not inform end user facing functionality and naming.

So, in the best interest of an end user, I would like to suggest to either

* make extra-01 and/or language-0* part of an existing lesson (to not create even more lessons)
* make extra-01 and/or language-0* their own lessons (e.g. renaming to lesson-17/18).
* make extra-01 and/or language-0* regular pages, removing all lesson-like naming and behavior, just linking them from within content.
* Remove extra-01 and/or language-0* (for the sake of completeness)

I slightly tend towards the first option (e.g. both topics are relevant in all languages and already exist in all languages). If that's not possible I'd opt for the third option. Option two makes sense, if for example all language and extra information could be turned into a fully fledged lessons, which make sense in all languages.

I am fine with any decision as long as these contents don't stay half lessons or lessonish contents.

**Comment by davidcarlisle** [comment]
Hi @jonasjacek  I still think I don't understand your concern that the language-xx are not in the table of contents. as I view it they are all in the table of contents, just that the table of contents has explanatory paragraphs between lesson 16 and language 01 and before extra-01.

As I said earlier if you think it would look better to have a single uniform list in the table of contents  that is certainly a possibility.  To an end user following the site navigation I don't think it matters much that the URL has lesson-xx or language-xx so I don't see why that should be confusing. but it is a useful distinction when organising the translations. Also I think it is good to keep the language specific lessons separate since they will end up being quite different from translated lessons. A lesson describing platex use for Japanese is not going to be at all like a lesson on babel shortcuts for German.  I don't think merging these into the main lessons helps the users, the distinction is a real difference.

**Comment by jonasjacek** [comment]
Hi @davidcarlisle, thank you for your quick reply. Did you see my suggestion to use includes to keep the language specifics out of the translation workflow? Although this might not work well for Japanese, you are right. :/

I will sleep another night to think about it. Uhhh. I see a separate TOC coming for stuff like that.

**Comment by davidcarlisle** [comment]
yes but I think end users as well as the translation authors benefit from the distinction.  They are a kind of "appendix". It helps explain the structure for the reader.  If the course had been written  originally for a  Japanese (or Chinese of even German) audience then it would be structured a bit differently; but this is an international course with a main core of translated lessons and extra set of language specific lessons  at the end with forward references to that where needed. I think that is a feature not a problem to be hidden.

**Comment by jonasjacek** [comment]
Should be done. I kept the structure and styled the language and extra lessons like all other lessons in the TOC. https://learnlatex.netlify.app/en/
