### ISSUE TITLE
Visualization of LaTeX / TeX on website

### ISSUE THREAD

**Issue by jonasjacek** [learnlatex/learnlatex.github.io#110]
In `_config.yml` there is the following configuration:

```
latex: "<span>L<span style='font-variant: small-caps; vertical-align:.35ex;margin-left:-.15em;margin-right:-.05em;'>a</span>T<span style='text-transform:uppercase; vertical-align:-.4ex;margin-left:-.1em;'>e</span>X</span>"
tex: "<span>T<span style='text-transform:uppercase; vertical-align:-.4ex;margin-left:-.1em;'>e</span>X</span>"
```
It allows for a certain visual presentation of the terms LaTeX and TeX in the front-end by including it with `{{ site.latex }}` and `{{ site.tex }}` in e.g. headings and paragraphs in HTML/Markdown.

I am unsure if it improves or harms the legibility of contents. I tend to the latter. I may come across as heretical with this idea but we should either use the special visual presentation everywhere or nowhere. 

Important: It will never work everywhere! For example, it will not work, where we use frontmatter to inform other elements like the table of contents. It will also not work with translation files (data files in `_data/`). This means, we will never be able to apply it everywhere.

In most texts its not applied yet. However, I've prepared this document, where it is used everywhere: https://learnlatex.netlify.app/en/lesson-01 - In my opinion in has a mild negative effect on readability.

**My questions to the community are:** 

- should we generally fall back to just LaTeX? (My suggestion)
- should we mix `{{ site.latex }}` and  `{{ site.tex }}` with LaTeX and TeX? (I advise against this)
- could we find a rule where to apply it and where not? (a kind of mixing, but following certain rules - which might be OK)

Thanks for your help.

**Comment by josephwright** [comment]
Personally, I feel that plain 'LaTeX' is best other than in 'cover pages', as for other logos. But I know this is ... a minority view.

**Comment by PhelypeOleinik** [comment]
I'm with Joseph.  Too many fancy `{{ site.latex }}` makes the text distracting.  Also, where `{{ site.latex }}` is used, it would be good if copy-pasting returns `LaTeX`, rather than the slightly awkward `L A TEX`

**Comment by Skillmon** [comment]
I might be wrong, but I thought we already had the consensus to only use it on displayed things and stick to `LaTeX` in the text. Maybe my memory tricks me here.

**Comment by davidcarlisle** [comment]
yes it was an experiment I put in early on,  it certainly doesn't work if used everywhere in the text. 

Personally I think it can be made to work well  if used just in headings (which is what we have in master) but actually comparing the TeX heading on the two versions of lesson-02 if we keep it it doesn't work so well with the noto sans condensed heading as it accentuates the condensed font with the negative kerning so would need re-spacing if we keep it. 

I have no objection to taking it out and see how it goes, it is easy enough to put it back in headings if we decide to go that way.

**Comment by jonasjacek** [comment]
I see a clear direction for me to go. I will remove it where I find it. Thanks for your quick help.
