### ISSUE TITLE
Fancy (La)TeX logo?

### ISSUE THREAD

**Issue by dbitouze** [learnlatex/learnlatex.github.io#122]
Why use plain text instead of fancy output of `\TeX` and `\LaTeX`?

**Comment by josephwright** [comment]
The LaTeX logo is exactly that: a logo. It's really intended for display situations, like book covers, not running text. That's before one gets into the 'fun' of substituting in running text written in Markdown.

**Comment by davidcarlisle** [comment]
@dbitouze  as you may recall we did experiment with using css still visible in my test site at
https://davidcarlisle.github.io/ll/en/lesson-01

![image](https://user-images.githubusercontent.com/1268738/106724577-45ae0e00-6600-11eb-96fc-79b9574084d2.png)

It was sort of OK for headings (far too distracting in text) but even in headings it's not really the TeX typeset logo and ends up being distracting. see issue #110

**Comment by davidcarlisle** [comment]
duplicate of #110
