### ISSUE TITLE
Anatomy of _an_ error

### ISSUE THREAD

**Issue by NiranjanTambe** [learnlatex/learnlatex.github.io#126]
[This](https://www.learnlatex.org/en/lesson-15#anatomy-of-a--error-message) section is named `Anatomy of a error` which should be `Anatomy of an error`.

**Comment by davidcarlisle** [comment]
Oh thanks, actually the markdown is

```
### Anatomy of a {{ site.tex }} error message
```

so it was **Anatomy of a LaTeX error message**  

we stopped using the css-styled latex logo but it seems to have dropped altogether. I'll fix 

There are over 40 uses of site.latex in headings
