### ISSUE TITLE
Write lesson: long documents

### ISSUE THREAD

**Issue by josephwright** [learnlatex/learnlatex.github.io#13]
Tracker issue for writing lesson 13.

**Comment by jimhefferon** [comment]
I brought in some material from latexref.xyz.  Not too sure about the biblio stuff because that depends on the biblio lesson.  

Also, Lamport says that for books *\maketitle* is pointless but I disagree with him.

**Comment by josephwright** [comment]
Great: I'd be tempted to cover `\tableof...`, `\include`, perhaps `\frontmatter`/`\appendix` here, plus I agree `\maketitle`. A few headers would make this nice and clear, but already looking good.

**Comment by jimhefferon** [comment]
It may make sense to change biblio stuff to match that lesson.  I'll wait to see what people think of that lesson.

**Comment by jimhefferon** [comment]
Sorry for a noob question.  In my lesson-07.md I write a minus sign in example-image, and on the screen it is converted to a dash of some sort, and so copy and paste doesn't compile.  What to do to circumvent that?

Jim

-----------
  Disinformation is false information spread deliberately to deceive. This is a subset of misinformation, which may also be unintentional.

The English word disinformation is a loan translation of the Russian dezinformatsiya, derived from the title of a KGB black propaganda department. Joseph Stalin coined the term, giving it a French-sounding name to claim it had a Western origin. Russian use began with a "special disinformation office" in 1923. Disinformation was defined in Great Soviet Encyclopedia (1952) as "false information with the intention to deceive public opinion". Operation INFEKTION was a Soviet disinformation campaign to influence opinion that the U.S. invented AIDS.



________________________________________

**Comment by Skillmon** [comment]
It is already 0x2212 in the raw source.

Jonathan

**Comment by jimhefferon** [comment]
OK, thanks.  I'll have another look.

Jim

-----------
  Disinformation is false information spread deliberately to deceive. This is a subset of misinformation, which may also be unintentional.

The English word disinformation is a loan translation of the Russian dezinformatsiya, derived from the title of a KGB black propaganda department. Joseph Stalin coined the term, giving it a French-sounding name to claim it had a Western origin. Russian use began with a "special disinformation office" in 1923. Disinformation was defined in Great Soviet Encyclopedia (1952) as "false information with the intention to deceive public opinion". Operation INFEKTION was a Soviet disinformation campaign to influence opinion that the U.S. invented AIDS.


________________________________________

**Comment by jimhefferon** [comment]
Joseph: what dis you mean by this?

> be tempted to cover \tableof..., \include, perhaps \frontmatter/\appendix here, plus I agree \maketitle. 

I briefly discussed them all except `\appendix`, which I just added, so I'm not sure.

This also I did not understand: 

> A few headers 

Did you mean `fancyhdr`?  Maybe in more?

**Comment by josephwright** [comment]
Based on the TeX FAQ search data, we should definitely include `\appendix` here.
