### ISSUE TITLE
Table of contents still picking up English headings.

### ISSUE THREAD

**Issue by NiranjanTambe** [learnlatex/learnlatex.github.io#133]
This issue is related to [this](https://github.com/learnlatex/learnlatex.github.io/issues/72#issuecomment-773008541) comment. Table of contents on my fork is for some reasons picking up English headings. See: https://niranjantambe.github.io/learnlatex.github.io/mr/#1-latex-basics (Though not always. See: https://niranjantambe.github.io/learnlatex.github.io/mr/#लाटेक्-आज्ञावल्यांचे-प्रदर्शन)

I checked the code for `lesson-01` and `extra-01` (which are the two files linked above) again and again, but found no significant difference in them. Can somebody please guide me?

**Comment by davidcarlisle** [comment]
The toc wording comes from each page in the top yml section eg lesson-01 has

```
toc-anchor-text: "LaTeX basics"
toc-description: "What LaTeX is and how it works."
```

You have translated that but I see it's not pulling the translated text in the table of contents.

If you look under settings on your at the github pages section do you see an error or is it building OK?

I can't see any error looking at the web view of your sources. I may fork your fork and clone it here later so I can see. I can't see anything wrong currently

**Comment by davidcarlisle** [comment]
@NiranjanTambe  found it..

in https://raw.githubusercontent.com/NiranjanTambe/learnlatex.github.io/master/mr/index.md

You still have


```
{% include toc-lessons.html prefix="en/lesson" %}
```

with `en` prefix, the extra and language-specific sections have been changed to `mr` which is why extra-01 works correctly

```
<h2 class="heading__toc">संकीर्ण प्रकरणे</h2>
<ul class="lessons-toc">
  {% include toc-additional-lessons.html prefix="mr/language" %}
  {% include toc-additional-lessons.html prefix="mr/extra" %}
</ul>
```

**Comment by NiranjanTambe** [comment]
Thanks :)

This solved the problem. Apologies for the mistake.

https://github.com/NiranjanTambe/learnlatex.github.io/commit/24d13e1c89b85f27f3ecfb15fffbed798bf4b8b6
