### ISSUE TITLE
Placement of "Next lesson" in lesson-16 looks a bit odd

### ISSUE THREAD

**Issue by joulev** [learnlatex/learnlatex.github.io#136]
lesson-15:

![image](https://user-images.githubusercontent.com/44609036/107866933-85021780-6ea8-11eb-96f9-0cd9e1463dcf.png)

lesson-16:

![image](https://user-images.githubusercontent.com/44609036/107866938-8e8b7f80-6ea8-11eb-801e-cc758510391e.png)

(Firefox 85)

**Comment by davidcarlisle** [comment]
This (and similar mis-placed links in the language-xx and extra-xx lessons) were fixed with additional css in commit 9f29233
