### ISSUE TITLE
Quotation mark inconsistency in English lessons

### ISSUE THREAD

**Issue by joulev** [learnlatex/learnlatex.github.io#137]
In more-01: “…” is used. However, in all other pages (it seems, not 100% sure) '…' is used.

What should be preferred?

(The current Vietnamese version also has some inconsistency, I will follow the one chosen here.)

**Comment by amunn** [comment]
Single quotes are most appropriate for most of the uses we need on the site, since they're usually reference to words not part of the sentence rather than actual quotations.
