### ISSUE TITLE
Renaming the master branch

### ISSUE THREAD

**Issue by davidcarlisle** [learnlatex/learnlatex.github.io#144]
In common with many other projects (and following the changed default
branch name at github) we  plan to rename the "master" branch to "main"

Github will redirect any Pull requests from forks to the master branch but
once the rename is done it would be better if any local clones or forks of
this repository renamed their branch to "main".

The following commands will rename the local branch and re-set tracking to the github repository main branch.
This should be done after the rename here.

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin main

```

**Comment by davidcarlisle** [comment]
Rename done

**Comment by davidcarlisle** [comment]
Also renamed in the articles repository of this GH organisation

**Comment by joulev** [comment]
@davidcarlisle Looks like www.learnlatex.org is down again. I am not sure but maybe you forgot to change the branch name in the GH Page settings.

**Comment by davidcarlisle** [comment]
the github UI changes the gh pages setting when you rename the branch, but you are right the site is gone let me push a change to force a rebuild

**Comment by davidcarlisle** [comment]
thanks for the heads-up I forced a rebuild and the site is back.

**Comment by josephwright** [comment]
https://github.community/t/publishing-with-pages-moving-master-to-main/118389/8

**Comment by davidcarlisle** [comment]
@josephwright  that's a bit old, the github interface does now automatically change the setting from master to main to build gh-pages. It just leaves it broken until you next push a change.

**Comment by josephwright** [comment]
@davidcarlisle  Er, but it's still not working ...

**Comment by davidcarlisle** [comment]
the site is now building from main, closing this issue.
