### ISSUE TITLE
Naming graphics files: advise only lowercase

### ISSUE THREAD

**Issue by dbitouze** [learnlatex/learnlatex.github.io#149]
About:

>Naming graphics files
>
>LaTeX works on many computer platforms so file names deserve some thought. Safest is to name your graphics simply, in particular without spaces. For example, if you want to organize your files by keeping all graphics in a subdirectory, then something like `\includegraphics[width=30pt]{pix/mom.png}` is portable and future-proof.
>
>Spaces in file names are traditionally somewhat problematic, but are now generally supported. However, if you have spaces in the name, and you have issues, you may wish to try removing the spaces as the first step.
>
>Accented character support is somewhat variable; there are issues with some systems, particularly on Windows. If you find issues with accented characters in file names, try using only ASCII characters for a test.

I would add the advice to use only lowercase characters in graphics files names. 

Indeed (AFAICS), it is not a problem on Windows if the (lower/upper)case of the graphics files names in the TeX source is not in compliance with the actual case of these files names, this OS seeming to not be sensitive to the case. But this is not portable e.g. on Linux (I used to experience this problem with files sent by colleagues or students).

**Comment by josephwright** [comment]
As long as the capitalisation in the `\includegraphics` line matches that of the file, all is well: that's the same for `\input` or `\include` or similar. I think in contrast to spaces, which have real low-level issues, capitalisation is relatively 'safe'.

**Comment by davidcarlisle** [comment]
hmm it's hard enough persading people to not use spaces and other weird characters, I'm not sure suggesting lowercase only would be popular.  The filename search is the same for `\includegraphics` as for `\input` so any suggestion should apply to all files not just graphics ones.  Since the texlive 2020 release kpathsea file searching has been (as a fallback) case insensitive even on case sentitive file systems.
