### ISSUE TITLE
Write lesson: Getting help and documentation

### ISSUE THREAD

**Issue by josephwright** [learnlatex/learnlatex.github.io#15]
Tracker issue for writing lesson 15.

**Comment by Skillmon** [comment]
I've added a bit on accessing documentation. Didn't start "getting help" yet. Can we collect ideas where to get help here? I'd put the mailing list there, latex.org, TeX.SX.

Should the localized QA-pages be included (e.g., technique.fr and texwelt.de)? Is it ok to include topanswers.xyz/tex there? Anything pressing we want to absolutely include that I miss out?

**Comment by josephwright** [comment]
I'd point to English resources in the English version: assuming we do go for translations, we can put language-specific support options there.

**Comment by Skillmon** [comment]
I'd also point to the various user groups here (also the language specific ones), though I'd avoid listing all the user groups there. More like pointing out that user groups exist and that those often have mailing lists as well.
