### ISSUE TITLE
Inconsistency regarding name of TeXLive.net service

### ISSUE THREAD

**Issue by joulev** [learnlatex/learnlatex.github.io#159]
In en/help.md, we have

> ##### Use a LaTeX online service
> 
> The <button>LaTeX Online</button> button, below the example, will submit the code to the [TexLive.net](https://texlive.net) service[^1].
> 
> The LaTeX CGI service was developed specifically to support this site, and in particular makes use of [PDF.js](https://mozilla.github.io/pdf.js/) to enable display of PDF on mobile and other browsers without built in PDF readers.
> 
> The resulting PDF document (or section of the error log) will be shown inline immediately below the example. A <button>Delete Output</button> button will be provided so that you may remove this output (or you may leave it in place and continue the rest of the lesson below).
> 
> Note that **LaTeX Online** requires no login or signup of any sort so it is very convenient for small examples, but neither this site nor the `latexcgi`, `latexonline.cc` or `latex-on-http` sites provide any mechanism to save your document. Any changes that you make to the example are lost if you move off the page.

To refer to TeXLive.net, "LaTeX online", "LaTeX Online", "TexLive.net", "LaTeX CGI", "LaTeX Online" (again), "`latexcgi`" have been used. That is three different names, and five different ways to write those names.

That is too inconsistent, isn't it? And not even one of them uses the correct capitalisation of the name used in https://texlive.net: TeXLive.net.

Currently I am updating vi/help.md, and I think I will choose "TeXLive.net" as the official name of the service.

**Comment by davidcarlisle** [comment]
Yes sorry about that. As you know, there is some "history" here.

I think technically I would say that the actual service is "latexcgi" and that is currently running at (at least) two sites: texlive.net and latexcgi.xyz but (especially as latexcgi.xyz will vanish once its 1 year AWS trial licence expires), that is a technical detail that we do not need to mention here so here I think we should just call it TeXLive.net here now.

The actual button is called "LaTeX online" partly to avoid committing to a specific domain name, but also historically as the first version was at latexonline.cc but that is probably confusing now.

@josephwright  and I did discuss changing the button name somewhere, I think in tex.sx chat not here.

Probably we should simply use TeXLive.net as the button text, or "Run at TeXLive.net" ?  to match "Open in Overleaf"  ? and normalise references to the service to call it TeXLive.net everywhere.

Suggestions welcome...

**Comment by joulev** [comment]
> Probably we should simply use TeXLive.net as the button text, or "Run at TeXLive.net" ? to match "Open in Overleaf" ? and normalise references to the service to call it TeXLive.net everywhere.

I prefer this approach.

**Comment by davidcarlisle** [comment]
@joulev  "Run at TeXLive.net" or simply "TeXLive.net"  for the button ?

**Comment by davidcarlisle** [comment]
OK let's see what @josephwright says but we'll probably do something...

**Comment by davidcarlisle** [comment]
@joulev I think I caught everything, the inconsistent capitalisation I fixed across all translations, the last two changes just in the `en` version for now.

**Comment by car222222** [comment]
The text for the button itself need not state exactly which service is being used.  Maybe best just something like:

Run LaTeX online

**Comment by davidcarlisle** [comment]
@car222222  that's exactly what it did say until yesterday, but it makes it hard to compare running latex online at Overleaf and running latex online at an unnamed service that isn't Overleaf and I don't think the experiment was totally successful. If we only supported one service that pubically was just seen as part of learnlatex it would be easier to not name the back end, but as it is now I think it works better to name the service being used. As @joulev says it had ended up being referred to as "LaTeX online" "texlive.net" with varying capitalisation, latexcgi and LaTeX CGI. I don't think it was clear that these always referred to the same thing, or to the service activated by the "run LaTeX online" button.
