### ISSUE TITLE
Allow translating (or transliterating?) the words given in the website footer "Planet".

### ISSUE THREAD

**Issue by niruvt** [learnlatex/learnlatex.github.io#187]
Along with `Navigation`, `Meta` we have a `Planet` section on the home page. The contents of that section are three links with titles respectively as the following:

1. The LaTeX Project
1. TeX Users Group
1. CTAN

Currently these titles are included in the `_includes/website-footer.html` file, but IMO there should be a provision to translate or transliterate them (in whichever script) and hence they should be included in the `_data/translations.yml`.

**Comment by niruvt** [comment]
PS: For Marathi these should be:

1. लाटेक् प्रकल्प
2. टेक् यूजर्स ग्रुप
3. सीटॅन

**Comment by joulev** [comment]
I think they are like brand names: they can be translated but shouldn't.

**Comment by niruvt** [comment]
> I think they are like brand names: they can be translated but shouldn't.

Is "The LaTeX Project" a brand name? Or just "LaTeX"? I think "The LaTeX project" is partially translatable.

and what about transliteration? I don't think transliterating brand names is not allowed. See for example: https://mr.wikipedia.org/wiki/मुखपृष्ठ. Here the brand name (i.e. Wikipedia) is unchanged, but written in Devanagari.

**Comment by joulev** [comment]
Oh now that you mentioned it, I forgot this type of "translation" happens in other languages too, like Katakana in Japanese.

Indeed, in this case, they should be translated.

**Comment by davidcarlisle** [comment]
@niruvt  can you check https://www.learnlatex.org/mr/ and close if that reads correctly, thanks

**Comment by niruvt** [comment]
That's really cool! Thanks. I am closing this issue :-)
