### ISSUE TITLE
Can we install dev versions of particular packages in LaTeX online service?

### ISSUE THREAD

**Issue by niruvt** [learnlatex/learnlatex.github.io#190]
I am planning to add a short paragraph on citations with `biblatex` for Marathi, but the code for Marathi localization is yet unreleased and present in the dev branch. To successfully compile the example given below we require `biblatex` v3.17 accompanied with `biber` v3.17 which are both unreleased. If there is a possibility to install the dev versions of both of these, I can write a short tutorial on Marathi citations in the extras maybe.

PS: We can also keep this choice optional in our `Settings` page with cookies.😄

```
\documentclass{article}
\usepackage{marathi}
\usepackage{biblatex}

\begin{filecontents}[overwrite]{test-bib.bib}
@article{निरंजन,
  author={निरंजन},
  title={भाषाभ्यासातील वाद व प्रवाद},
  journaltitle={आलोक मराठी नियतकालिक},
  pages={२-९},
  date={२०२१-०१-२४},
  series={१},
  note={बुलढाणा: वर्णमुद्रा प्रकाशन}
}
\end{filecontents}

\addbibresource{test-bib.bib}

\begin{document}
\cite{निरंजन}

\printbibliography
\end{document}
```

**Comment by josephwright** [comment]
How would a user be expected to access these? Burning-edge features don't feel appropriate for a beginner's tutorial to me.

**Comment by niruvt** [comment]
> How would a user be expected to access these?

You mean on their local systems?

**Comment by davidcarlisle** [comment]
For the tutorial itself of course you don't need tex at all so you can describe the latest version with a note saying what is available.

As you know it is theoretically possible to add files to each project upload (as I did for `marathi.sty` when overleaf had an old version of texlive without that package) but that is not very convenient and only suitable for single small files, certainly I could not upload a new babel and new biber every time you run a document.

If the files are in texlive and you need pdflatex-dev then that can already work with the texlive.net server. If the files are not yet in texlive then they are not going to be available to most users so it would probably be condfusing 

I just ran your example at texlive.net the log has some warnings and I can not read the script to see how bad it is, but it did something, so it is perhaps best to just say in your tutorial text that later versions will have new features.

https://texlive.net/run?%25!TEX%20xelatex%0A%25!TEX%20biber%0A%5Cdocumentclass%7Barticle%7D%0A%5Cusepackage%7Bmarathi%7D%0A%5Cusepackage%7Bbiblatex%7D%0A%0A%5Cbegin%7Bfilecontents%7D%5Boverwrite%5D%7Btest-bib.bib%7D%0A@article%7B%E0%A4%A8%E0%A4%BF%E0%A4%B0%E0%A4%82%E0%A4%9C%E0%A4%A8,%0A%20%20author=%7B%E0%A4%A8%E0%A4%BF%E0%A4%B0%E0%A4%82%E0%A4%9C%E0%A4%A8%7D,%0A%20%20title=%7B%E0%A4%AD%E0%A4%BE%E0%A4%B7%E0%A4%BE%E0%A4%AD%E0%A5%8D%E0%A4%AF%E0%A4%BE%E0%A4%B8%E0%A4%BE%E0%A4%A4%E0%A5%80%E0%A4%B2%20%E0%A4%B5%E0%A4%BE%E0%A4%A6%20%E0%A4%B5%20%E0%A4%AA%E0%A5%8D%E0%A4%B0%E0%A4%B5%E0%A4%BE%E0%A4%A6%7D,%0A%20%20journaltitle=%7B%E0%A4%86%E0%A4%B2%E0%A5%8B%E0%A4%95%20%E0%A4%AE%E0%A4%B0%E0%A4%BE%E0%A4%A0%E0%A5%80%20%E0%A4%A8%E0%A4%BF%E0%A4%AF%E0%A4%A4%E0%A4%95%E0%A4%BE%E0%A4%B2%E0%A4%BF%E0%A4%95%7D,%0A%20%20pages=%7B%E0%A5%A8-%E0%A5%AF%7D,%0A%20%20date=%7B%E0%A5%A8%E0%A5%A6%E0%A5%A8%E0%A5%A7-%E0%A5%A6%E0%A5%A7-%E0%A5%A8%E0%A5%AA%7D,%0A%20%20series=%7B%E0%A5%A7%7D,%0A%20%20note=%7B%E0%A4%AC%E0%A5%81%E0%A4%B2%E0%A4%A2%E0%A4%BE%E0%A4%A3%E0%A4%BE:%20%E0%A4%B5%E0%A4%B0%E0%A5%8D%E0%A4%A3%E0%A4%AE%E0%A5%81%E0%A4%A6%E0%A5%8D%E0%A4%B0%E0%A4%BE%20%E0%A4%AA%E0%A5%8D%E0%A4%B0%E0%A4%95%E0%A4%BE%E0%A4%B6%E0%A4%A8%7D%0A%7D%0A%5Cend%7Bfilecontents%7D%0A%0A%5Caddbibresource%7Btest-bib.bib%7D%0A%0A%5Cbegin%7Bdocument%7D%0A%5Ccite%7B%E0%A4%A8%E0%A4%BF%E0%A4%B0%E0%A4%82%E0%A4%9C%E0%A4%A8%7D%0A%0A%5Cprintbibliography%0A%5Cend%7Bdocument%7D

**Comment by niruvt** [comment]
> I just ran your example at texlive.net the log has some warnings and I can not read the script to see how bad it is, but it did something.

I just checked, but it is (obviously) not using the [`marathi.lbx`](https://github.com/plk/biblatex/blob/dev/tex/latex/biblatex/lbx/marathi.lbx) which is unreleased and only present on the `dev` branch.

>  I could not upload a new babel and new biber every time you run a document.

No problem. I will close the request.
