### ISSUE TITLE
The LaTeX source editing form captures the TAB key

### ISSUE THREAD

**Issue by jfine2358** [learnlatex/learnlatex.github.io#197]
The LaTeX source editing form captures the TAB key. There's no obvious way to use that form if you don't have or can't use a mouse. This makes editing of LaTeX source harder and perhaps impossible for those with dexterity or visual impairments.

For example try editing the sample code in https://www.learnlatex.org/en/lesson-03 without use the mouse (or trackpad).

**Comment by davidcarlisle** [comment]
Hmm yes, you can tab thriugh the various controls until you get to th eeditor then it adds tab and you seem to be stuck

https://stackoverflow.com/questions/35520120/ace-editor-change-field-focus-on-tab-key

suggests I could turn that off so tab stayed as the browser focus key but then you can't enter a tab. For TeX that's probably not a big loss but it would be nice to have both.

In an editor I think I'd expect tab to add tab (or spaces to indent or whatever the tab setting is) but there ought to be a keyboard ctrl-tab or something to move focus off the editor.

I'll see what I can do....

**Comment by davidcarlisle** [comment]
Incidentally there is a request at

https://github.com/davidcarlisle/latexcgi/issues/2

to use codemirror instead of ace as the editor (and a link to a test of that in that issue) but that has exactly the same behaviour as far as I can see.

**Comment by davidcarlisle** [comment]
https://github.com/ajaxorg/ace/issues/3149

**Comment by davidcarlisle** [comment]
codemirror 6 (next version) seems to have this feature. the test here

https://codemirror.net/6/examples/tab/

works for me with tab and escape tab being the two behaviours.

The codemirror test I gave above is the current version 5 (which has methods to do this as well, but not enabled by default) so probably I should look to switching to codemirror 6 then this will fix itself.

**Comment by davidcarlisle** [comment]
@jfine2358 I decided to fix this as shown in stackexchange for ACE (the tab indent/unindent facility is also bound to ctrl-] and ctrl-[ so still available) it works for me in firefox and chrome, can you check it works in your setting (there are lots of browser dependencies here) if so I'll close this although it'll need checking again if we switch to codemirror.
