### ISSUE TITLE
Libre-JS compatibility?

### ISSUE THREAD

**Issue by niruvt** [learnlatex/learnlatex.github.io#199]
Currently when LibreJS is turned on in my firefox, it complains about one Javascript loaded by our site and blocks it. The following is it's basic information:

```
/**
 * AnchorJS - v4.1.0 - 2017-09-20
 * https://github.com/bryanbraun/anchorjs
 * Copyright (c) 2017 Bryan Braun; Licensed MIT
 */
```

I am not an expert in this area, but I would be glad if we stay LibreJS-compatible. Thoughts?

**Comment by davidcarlisle** [comment]
As you show anchor.js is MIT licenced so certainly a free licence in the sense required by libre-js so this appears to be a false positive where it is simply flagging a javascript library that it doesn't already know,

I don't use libre-js myself but I just checked the manual at its main repository and as far as I can see you can whitelist anchorjs
in your librejs configurations

> Scripts may be blacklisted or whitelisted through the pop-up menu box.

https://www.gnu.org/software/librejs/free-your-javascript.html

says

> There are too many JavaScript libraries and versions of those libraries for LibreJS to keep track of, so you will likely need to add license information for the libraries you use. By looking at the source code or checking the upstream site, you should be able to tell what license is being used. 

So it appears to be not unexpected that you need to explicitly whitelist some javascript libraries.

I'll close with no action, but re-open if you think I have missed an issue here and there is something we can do.
