### ISSUE TITLE
Linking between lessons

### ISSUE THREAD

**Issue by Skillmon** [learnlatex/learnlatex.github.io#20]
I want to link to lesson 15 from within lesson 8 (since I want to mention `booktabs` documentation for its guides on pretty tables).

Is there anything set up already to link between lessons?

**Comment by josephwright** [comment]
You should be able to use standard Markdown links, so
```
see [lesson X](/en/lesson-X)
```
or similar.

**Comment by davidcarlisle** [comment]
or even just `[Lesson 2](lesson-02)` since they are all in the same directory, relative URL should work.

**Comment by josephwright** [comment]
I think we have a plan here.
