### ISSUE TITLE
Missing `endraw`s?

### ISSUE THREAD

**Issue by dbitouze** [learnlatex/learnlatex.github.io#212]
In [this typical example](https://github.com/learnlatex/learnlatex.github.io/blob/main/en/lesson-13.md?plain=1) of [javascript `preincludes` array](https://davidcarlisle.github.io/latexcgi/#multifile-projects), some opening [`<!-- pre⟨n⟩ {% raw %} -->`s](https://github.com/learnlatex/learnlatex.github.io/blob/78cd8e4c16fd19a408119ded043f7258d87dc4cd/en/lesson-13.md?plain=1#L158) are closed with their corresponding [`<!-- {% endraw %} -->`s](https://github.com/learnlatex/learnlatex.github.io/blob/78cd8e4c16fd19a408119ded043f7258d87dc4cd/en/lesson-13.md?plain=1#L163), some others [aren't](https://github.com/learnlatex/learnlatex.github.io/blob/78cd8e4c16fd19a408119ded043f7258d87dc4cd/en/lesson-13.md?plain=1#L147). Is it intended?

**Comment by davidcarlisle** [comment]
I suspect it wasn't intended, and the jekyll documentation only ever seems to mention matching `raw` and `endraw`  on the other hand I'm not sure it's needed at all, mostly a normal code block is fine you just need to use  `raw` sometimes to prevent the liquid or markdown filters mis-interpreting tex constructs such as `{%`   It certainly looks wrong as it is. 

I'll check later, thanks for the report.
