### ISSUE TITLE
Add Chinese Simplified Transltion

### ISSUE THREAD

**Issue by syx-413** [learnlatex/learnlatex.github.io#214]
Seeing that there was a zh in the folder, I would be happy to work on the Chinese Simplified Chinese translation；
😊

**Comment by davidcarlisle** [comment]
@syx-413  there is a fork started at https://github.com/CTeX-org/learnlatex.github.io/tree/zh-Hans/zh-Hans  we'd be happy to merge this to the main site once it's ready. (@stone-zeng)

**Comment by davidcarlisle** [comment]
@syx-413 you could also review #221
