### ISSUE TITLE
Example code not compilable: \usepackage after \begin{document}

### ISSUE THREAD

**Issue by joulev** [learnlatex/learnlatex.github.io#23]
https://github.com/learnlatex/learnlatex.github.io/blob/3463b56fa5d7729e8c2a8639a7d4b000ba5c4b97/en/lesson-08.md#L154-L158

I suppose that is a typo? Needless to say, `\usepackage` is not allowed inside `document`.

**Comment by Skillmon** [comment]
@joulev thanks for spotting this. Yes, this obviously is a "typo" which came into existing when we added the `\documentclass{article}` and `\begin{document}...\end{document}` to the examples so that the building blocks of the site work.
