### ISSUE TITLE
Write lesson: Your first LaTeX document

### ISSUE THREAD

**Issue by josephwright** [learnlatex/learnlatex.github.io#3]
Tracker issue for writing lesson 3.

**Comment by jimhefferon** [comment]
I'm not sure about showing output or how closely we are tied to Overleaf, etc.  But I put in content that I hope is a good start.  This is based on the document that Karl and I have on CTAN, first-latex-doc.

**Comment by josephwright** [comment]
We are not tied to Overleaf other than wanting to have a way of 'edit this file now' or similar.

I wonder if we might take the content you have and spread it across the other 'lessons': at present, it covers quite a lot of what we want to have in. What I think we do want is more detail for the lines that make up a minimal document: things like 'All `\LaTeX` documents start with ...'.

Looking good as a starting point :)

**Comment by jimhefferon** [comment]
Whatever changes suit would be great.  As I say, Karl and I had some content and I wanted to pour it in somewhere.

Jim


________________________________________

**Comment by jimhefferon** [comment]
I redistributed some of the material that I had put in lesson-3 to 3, 4, 5, and 10.  There is more but I have to do something else now.

I'm not sure exactly what to put in the CHANGELOG.  Could someone give an example?

Jim

-----------
  Be well, stay well.  Vote against the moron.


________________________________________

**Comment by josephwright** [comment]
Don't worry about the CHANGELOG yet: we are at the set up phase so there is no real need to say anything. We'll start formal changes once we go 'live'.

**Comment by josephwright** [comment]
This one looks pretty much done to me :)
