### ISSUE TITLE
Demonstrate the `table` environment

### ISSUE THREAD

**Issue by Skillmon** [learnlatex/learnlatex.github.io#30]
Currently the lesson-08 (tables) only demonstrates the `tabular` environment and the more-08 section shows some extensions of it. But the actual `table` environment isn't shown.

Lesson-07 is about getting images into the document and making things float. Imho, it would be better to move lesson-08 prior to lesson-07, so that in the current lesson-07 we can show the `table` environment without having to explain `tabular`. The reasoning for this is, that lesson-08 is pretty long already and it wouldn't cost much to add it to lesson-07.

Thoughts?

**Comment by josephwright** [comment]
I'm happy to say about the `table` environment in lesson 7, and there's no strong reason for the order we have, except that tables are a bit scary. How do others see this?

**Comment by davidcarlisle** [comment]
could swap the order but currently at least that table one is a lot more technical than the floats and graphics. As it's the next lesson I don't think it would be too bad to have a really simple tabular example float and a forward reference "to tables are described in the next lesson"..

**Comment by davidcarlisle** [comment]
more-08 now has three `table` enviroment examples and more-07 has a forward reference to the tables lesson 8, so while more could be done, I don't think there is enough here to need a restructuring and getting all translations updated, so I suggest we close as done?  @josephwright  @Skillmon  ?
