### ISSUE TITLE
How to add a translation?

### ISSUE THREAD

**Issue by joulev** [learnlatex/learnlatex.github.io#35]
I want to add a Vietnamese translation. (Well not sure if I will succeed, but I want to give it a try.)

However, I don't find any instructions on how to do so.

As I can see, I will write the translations to `vi` directory. So I copied all stuff in `en` to `vi` and translate whatever can be translated in the markdown files.

Now I have no idea how to build the site and see the result after that. I am not confident enough to send a PR without any testing at all, so I need to at least see what my code is doing in my browser. However these web-related things are higher than what I know now.

So how to set up a development environment that I can test in my local machine?

**Comment by davidcarlisle** [comment]
Note that at present we are not recommending that people do translations yet as the English source is still being actively edited.

We have added  three sample translations with _just_ the headings translated, mainly to test the language switching mechanisms are working before we need them for real translations.

That said the easiest way to test is to make a fork of th repository and enable guthub pages in the fork then the new version will be available at

https://joulv.github.io/learnlatex

when you are happy with it there you can make a pull request to merge back.

You should just need to copy the de directory to vi and add vi to the list of languages in `_config.yml`

**Comment by davidcarlisle** [comment]
actually your fork is called learnlatex.github.io so I think it will appear in gh-pages as

https://joulv.github.io/learnlatex.github.io

**Comment by joulev** [comment]
Thanks. GitHub returned some `CNAME` warnings and those warnings worried me (did not even know they are only warnings and not errors). Now it is working.

**Comment by davidcarlisle** [comment]
@joulev  delete the CNAME from your file, that is trying to make your copy _be_ learnlatex.org

**Comment by joulev** [comment]
Oh, I see, somehow my eyes didn't see the file sitting there. Now I hope there will be no warnings ;)

**Comment by davidcarlisle** [comment]
actually I'm re-opening, as at some point we do need to make more complete documentation on how to do this.

If you think of anything that should be put in that documentation as you experiment, feel free to leave a comment here

**Comment by davidcarlisle** [comment]
Since you forked I added localisation for the buttons "edit", "copy" etc, so the `includes` directory will need a `buttons.js` equivalent to this one (for German)

```
var buttons ={
    "edit":             "Bearbeiten",
    "copy":             "Kopieren",
    "Open in Overleaf": "In Overleaf öffnen",
    "LaTeX.Online":     "Latex.Online",
    "Delete Output":    "Fenster schließen"
}
```

**Comment by davidcarlisle** [comment]
A first draft of guidelines for translators has been added as

https://www.learnlatex.org/TRANSLATIONS

**Comment by davidcarlisle** [comment]
I'm going to close this issue now we have https://www.learnlatex.org/TRANSLATIONS  please feel free to open new issues suggesting additions or changes to that file if you think of anything.
