### ISSUE TITLE
The word "must" misused?

### ISSUE THREAD

**Issue by joulev** [learnlatex/learnlatex.github.io#37]
Look at line 73 (L74 and L75 are only for extra context).

https://github.com/learnlatex/learnlatex.github.io/blob/1e1f1daaefe0adbd7054e2b99324b8d2f3dd1098/en/lesson-03.md#L73-L75

Why must I nest environments? I am not a native speaker so I may be wrong, but I believe "can" is more suitable. Something like this is IMHO better:

```markdown
You can also nest them, but make sure they are matched: 
if you have `\begin{x} ... \begin{y}` then you must have 
 `\end{y} ... \end{x}`. 
```

**Comment by rvente** [comment]
If I may offer my opinion -- I read it in the same way as "You must nest them **such that** if you have..." To simplify, it would become "If you nest them like..., then you must..." So I wouldn't say misused, but perhaps there's a little space for clarity.

**Comment by josephwright** [comment]
@rvente Sounds about right to me: I'll adjust. Thanks.
