### ISSUE TITLE
Document \hline in lesson-08

### ISSUE THREAD

**Issue by joulev** [learnlatex/learnlatex.github.io#41]
en/lesson-08.md doesn't document `\hline` at all. In fact, `\hline` doesn't exist in the whole page.

I know users should be recommended to use `booktabs` commands, but `\hline` is standard and I see no reason in documenting `|` without documenting `\hline`.

**Comment by josephwright** [comment]
This was a deliberate change: lesson 8 was pretty large. The aim of the site is to promote a core 'best practice' set of information, and `\hline` is really not part of that.

**Comment by joulev** [comment]
Ah, it is in more-08. Sorry for the noise.
