### ISSUE TITLE
Link to texdoc.net is too long

### ISSUE THREAD

**Issue by joulev** [learnlatex/learnlatex.github.io#43]
https://github.com/learnlatex/learnlatex.github.io/blob/b3776f87781b32ec451914632493cb6df3918873/en/more-15.md#L13-L19

The links are too long, aren't they?

For example, with `source2e.pdf`, you can use either of the following
* http://texdoc.net/pkg/source2e
* http://texdoc.net/show.php?pkg=source2e

**Comment by davidcarlisle** [comment]
Thanks fixed with aec6f7c
