### ISSUE TITLE
Pasting to the editor gives HTML result instead of plain text result

### ISSUE THREAD

**Issue by joulev** [learnlatex/learnlatex.github.io#45]
When copy-paste code from a webpage to the editor in learnlatex.org, the HTML part of the code is also copied. For example, have a look at the following code

```tex
\documentclass{article}
\begin{document}
Hello, world
\end{document}
```

How it is displayed in my browser:

![image](https://user-images.githubusercontent.com/44609036/84653672-0b401580-af38-11ea-9c22-f541d94568c2.png)

Copy it and paste to learnlatex.org:

![image](https://user-images.githubusercontent.com/44609036/84653605-ef3c7400-af37-11ea-99e4-97de0be381f3.png)

[still compilable with LaTeX Online, not yet tested with Overleaf]

When pasting, all formatting of the code should be removed, leaving only the plain text. For example this is, I believe, the intended behaviour: that very piece of code pasted to https://paste.ubuntu.com:

![image](https://user-images.githubusercontent.com/44609036/84653783-362a6980-af38-11ea-9220-247fbb4747a1.png)

**Comment by davidcarlisle** [comment]
Yes, actually re-clicking the edit button will remove the formatting, as it does with the original syntax highlighting on the site but I should accept the plain text version. I'll fix thanks.

Actually I would have liked to keep the syntax highlighting while editing but the behaviour  seems unpredictable and browser specific, in particular once inside a styled span, the return key doesn't add a newline so removing all highlighting seemed safest.

Something like this I guess

https://stackoverflow.com/questions/53186433/restrict-paste-in-contenteditable-html-js

**Comment by davidcarlisle** [comment]
As far as I can see this now works as expected in the ACE editor, closing feel free to re-open if there are issues.
