### ISSUE TITLE
Should /en be redirected to / or the other way round?

### ISSUE THREAD

**Issue by joulev** [learnlatex/learnlatex.github.io#48]
Currently https://www.learnlatex.org/en redirects to https://www.learnlatex.org.

This is imho inconsistent, as the welcome page of all other languages are located at https://www.learnlatex.org/[language].

Should the redirect goes the opposite way, i.e. https://www.learnlatex.org redirects to  https://www.learnlatex.org/en? That is better to me.

**Comment by davidcarlisle** [comment]
One issue is that it's only a second class client-side redirect via an HTML `<meta http-equiv="refresh"` element.

Hosting on github pages means that we can not set up server side redirect rules.

This means for example that clients may or may not see the redirect depending on whether they interpret the HTML and choose to follow it.

I just tested with

 `wget https://www.learnlatex.org/en` 

and it fetched the stub redirect file not the real index page as it would if there had been a redirect specified in the HTTP headers.

So... switching round the redirect may leave the site home page looking a bit empty to some clients/crawlers.

Another possible solution would be to separate the pages and have an English language welcome page on /en  and some different introduction written in English but covering all the translations at the real top level. Then we would not need a redirect at all.

Something for our site designer to think about, possibly.

**Comment by joulev** [comment]
> Another possible solution would be to separate the pages and have an English language welcome page on /en and some different introduction written in English but covering all the translations at the real top level. Then we would not need a redirect at all.

That sounds most sensible to me.

**Comment by davidcarlisle** [comment]
Note there is some precedence on other high profile sites for the redirects as we have them, eg

https://letsencrypt.org/en/  redirects to https://letsencrypt.org/

https://letsencrypt.org/vi/ shows the translation

**Comment by josephwright** [comment]
I think in general people do have `en` -> root and 'other languages' separately, at least where the 'common case' is in English.

**Comment by josephwright** [comment]
I'm assigning this to @jonasjacek as it's a web development question really: I'd like his input.

**Comment by jonasjacek** [comment]
It's on the list of things to define. The current implementation is definitely not final and I haven't started working yet. This will be addressed shortly, though.

**Comment by jonasjacek** [comment]
It may not look nice yet, and there still might be some broken links, but from the technical and information architecture side, it is done. You can test it at https://learnlatex.netlify.app/.
