### ISSUE TITLE
Illustrate the differences between natbib and biblatex

### ISSUE THREAD

**Issue by fritzw** [learnlatex/learnlatex.github.io#49]
I was reading lesson-12.md (Citations and references) and it left me a bit confused what the differences between the two methods are. In which situations would I choose `natbib` over `biblatex` or vice versa? I imagine a novice LaTeX user would expect some guidance like "if you don't need Feature XY, don't worry and just use Package Z" or something similar.

PS: Cool project.

**Comment by joulev** [comment]
It is actually written in [more-12](https://www.learnlatex.org/en/more-12#dealing-with-non-english-sorting).

As I understand, both packages are recommended equally for English users and biblatex is preferred when you work with foreign languages.

**Comment by moewew** [comment]
It may be worth considering mentioning that `biblatex` cannot work with `.bst` files and that people will need the classical BibTeX approach there. There are many templates and publisher/university classes out there that come with a `.bst` file, so quite some people are going to encounter `.bst` files sooner or later.

I don't know how deep the `more-...` sections should go, but it may be useful to also mention manual `thebibliography`/`\bibitem` and BibTeX without `natbib` there.

**Comment by josephwright** [comment]
We likely should have some guidance in the basic lesson. My preference there would be to say that `natbib` is good if there is a style, otherwise use `biblatex`.

I'd like to avoid manual `\bibitem` stuff: really this is _very_ specialist.

**Comment by moewew** [comment]
It may be worth keeping in mind that not all styles are compatible with `authoryear` `natbib` (and `\citet` even in `numbers` mode).

Fair enough about `\bibitem`. I was thinking it might get a short mention in the *more* section. There are some publisher/journal templates out there that come without `.bst` files and use `thebibliography`.

**Comment by josephwright** [comment]
@moewew I've assigned to you: perhaps put in a PR?

**Comment by moewew** [comment]
A first attempt is at https://github.com/learnlatex/learnlatex.github.io/pull/74. Feedback would be welcome.
