### ISSUE TITLE
[Lesson-04] Lists: descriptive lists as well

### ISSUE THREAD

**Issue by dbitouze** [learnlatex/learnlatex.github.io#50]
In lesson-04, I would mention also descriptive lists in section "Lists" with something like:

> There are two common types of list built in to LaTeX.
> [...]
>Notice that we use \item to start each entry, and that the marker used for each type of list is added automatically.
> Another type of list, less common, is the "descriptive lists":
>```latex
>\begin{description}
>  \item[An object:] description of this object.
>  \item[Another object:] description of this another object.
>  \item[Still another object:] description of this still another object.
>\end{description}
>```

**Comment by joulev** [comment]
I think that is not quite basic enough for the main lesson, but perhaps it should be mentioned in the additional lesson.

**Comment by josephwright** [comment]
Can you make a pull request?

**Comment by dbitouze** [comment]
@josephwright Done.
