### ISSUE TITLE
Images showing the results of the codes

### ISSUE THREAD

**Issue by dbitouze** [learnlatex/learnlatex.github.io#52]
Being able to edit, copy, Open in Overleaf and  in LaTeX Online are great features. But it would be nice for the reader to immediately see the results of the codes with images attached to each code blocks. 

Moreover, it would be more energy-friendly: less Internet traffic, less servers requested, etc.

**Comment by joulev** [comment]
I am personally against this idea. LaTeX Online is imho good enough, and for some reason if LaTeX Online doesn’t work the user can always use Overleaf or their own locally installed TeX distributions.

**Comment by joulev** [comment]
Note that if you include output images, all features you listed (edit, ~~copy~~, Overleaf, LaTeX Online) are basically useless as probably they will never be used. The learner will say “well I have the code and I have the output. Why would I compile the code just to get that output again?”

**Comment by dbitouze** [comment]
@joulev 
> Note that if you include output images, all features you listed (edit, ~copy~, Overleaf, LaTeX Online) are basically useless as probably they will never be used.

Not sure (see below) and not a big drama.

> The learner will say “well I have the code and I have the output. Why would I compile the code just to get that output again?”

Yes, they will be used by the learner who wants to play with the examples, or the one who is not sure to understand and has to experiment to be convinced. I guess the other ones (notably those for which the lessons are clear enough) would be happy to not have to switch to another site just to check the results they guess.

**Comment by davidcarlisle** [comment]
@dbitouze  it was a conscious decision not to include output images when we set up the site. It could of course be changed fairly easily but I think we'd want to get more real user experience before changing this.

Requiring that you run latex (hopefully) strengthens the interactive feel of the site and distinguishes it from other static tutorials. While overleaf does obviously switch you off site, the fact that the latex online button is technically using a different site as the back end service should not be noticeable to the reader, and hopefully the examples are small enough that there is no appreciable wait. The resulting output is shown "in the page" even if technically it's an iframe referencing the latex online service.

As I say, nothing is fixed and if user testing shows that it would be better to have images, then we could certainly set up a commit hook to generate the required images whenever a lesson is edited and pushed to github, but currently I quite like the notion that you have to run latex to see the output.

**Comment by joulev** [comment]
@dbitouze 

> [...] I guess the other ones (notably those for which the lessons are clear enough) would be happy to not have to switch to another site just to check the results they guess.

Although those buttons works with external sites, the user doesn’t need to “literally” switch to another site. He can simply press the LaTeX Online button and the output will appear as if no third-party sites were used.

For those who find the lessons clear enough, (1) why would they need the site in the first place? (2) They already know what the output looks like, so the images are of no use. Anyway I don’t think this site should be designed more for the experts than for the newbies.

**Comment by dbitouze** [comment]
@davidcarlisle 

> @dbitouze it was a conscious decision not to include output images when we set up the site. It could of course be changed fairly easily but I think we'd want to get more real user experience before changing this.

OK.

> Requiring that you run latex (hopefully) strengthens the interactive feel of the site and distinguishes it from other static tutorials.

As I said, this interaction is nice but could be in addition to output images.

> While overleaf does obviously switch you off site, the fact that the latex online button is technically using a different site as the back end service should not be noticeable to the reader,

AFAICS, it generates a PDF which is automatically downloaded so depending on you're setting, you may have to click somewhere to see the output: not very handy. BTW, it doesn't work well here (file downloaded again and again until "Delete the output" is clicked) but I'll open a separate issue.

> and hopefully the examples are small enough that there is no appreciable wait. The resulting output is shown "in the page" even if technically it's an iframe referencing the latex online service.

It should depend on the browser settings, since it doesn't work like this here (see above).

> As I say, nothing is fixed and if user testing shows that it would be better to have images, then we could certainly set up a commit hook to generate the required images whenever a lesson is edited and pushed to github, but currently I quite like the notion that you have to run latex to see the output.

OK.

**Comment by dbitouze** [comment]
> @dbitouze
> 
> > [...] I guess the other ones (notably those for which the lessons are clear enough) would be happy to not have to switch to another site just to check the results they guess.
> 
> Although those buttons works with external sites, the user doesn’t need to “literally” switch to another site. He can simply press the LaTeX Online button and the output will appear as if no third-party sites were used.

Not with configuration (see my comment to @davidcarlisle).

> For those who find the lessons clear enough, (1) why would they need the site in the first place?

To learn LaTeX.

> (2) They already know what the output looks like,

Know, no. Guess, yes.

> so the images are of no use.

Yes, to confirm what they guess.

Maybe, the images could be hidden by default and a button "Want to see what you guess from the code?" could reveal them.

> Anyway I don’t think this site should be designed more for the experts than for the newbies.

Agree. But there are different kinds of newbies.

**Comment by davidcarlisle** [comment]
> AFAICS, it generates a PDF which is automatically downloaded so depending on you're setting, you may have to click somewhere to see the output: not very handy.

Ah I did wonder if you were seeing that.

I have a plan to address that but it's on a test server that's not ready to be public yet.

I see it on mobile but you can also see it on a desktop browser if you have configured it to open an external pdf viewer rather than use the browsers pdf renderer.

If you want to look drop me an off-site email and I'll give you a link, I'd be interested to know if it's better for you.

David

**Comment by josephwright** [comment]
I wonder how the design would look with both images and 'live' output. This could get very cluttered. As @davidcarlisle  says, the original plan was to use the demos and have students compile their own output: that's how it works when you run a course face-to-face.

**Comment by davidcarlisle** [comment]
@josephwright  Denis's experience is clouded by the fact that  he's not seeing the result in-page: just an empty white iframe, with the pdf appearing in an external browser; see issue #53. I suspect we need to fix that sooner rather than later, although requires requesting the latex servers provide an option to serve via pdf.js (or providing such a server ourselves).

**Comment by dbitouze** [comment]
> I wonder how the design would look with both images and 'live' output.

Images could be in the right margin.

> This could get very cluttered.

With the images in the right margin, it would look like many LaTeX editors: source in the left-hand side, facing the result in the right-hand side.

> As @davidcarlisle says, the original plan was to use the demos and have students compile their own output: that's how it works when you run a course face-to-face.

Do you mean a LaTeX course? If so, not in my case: as a first step, I explain the principles with [beamers](https://gte.univ-littoral.fr/Members/denis-bitouze/pub/latex/diapositives-cours-d) containing a lot of examples of sources with their accompanying results; as a second step, students practice and compile their own output with [exercises](https://gte.univ-littoral.fr/Members/denis-bitouze/pub/latex/exercices).

**Comment by jonasjacek** [comment]
I am with @joulev on this one.

> Note that if you include output images, all features you listed (edit, ~copy~, Overleaf, LaTeX Online) are basically useless as probably they will never be used. The learner will say “well I have the code and I have the output. Why would I compile the code just to get that output again?”

Especially if the original plan was to use the demos and have students compile their own output.

However, if you would like to have images, now is the time to let me know, so I can come up with a style for them.

**Comment by davidcarlisle** [comment]
I think we shouldn't provide images as noted above. The problem at the time that PDF results were not showing by default in some browser configurations has been addressed by using pdf.js by default so the PDF rendering should work in all common desktop and mobile browsers. Having users need to run latex to see the result is I think a distinguishing feature of the site.
