### ISSUE TITLE
Suggestion: remove edit and copy fields in examples

### ISSUE THREAD

**Issue by pgundlach** [learnlatex/learnlatex.github.io#55]
A suggestion: please remove the edit and copy buttons at the top of the examples:

<img width="1001" alt="latex example w/ button at the top" src="https://user-images.githubusercontent.com/209434/86450422-d09cf200-bd19-11ea-85ae-3eb3dd068d64.png">

IMO it is better to allow editing right away and copying can be done with the keyboard or push the button to the bottom.

<img width="997" alt="latex example without button at the top" src="https://user-images.githubusercontent.com/209434/86450711-3db08780-bd1a-11ea-975e-c1e9ad4f36f3.png">

I  think the second is easier to follow. 

I know that design will be added later on, so can just take this as a suggestion and close the issue.

This is for example how the Go documentation look in "Dash":

<img width="1274" alt="go documentation" src="https://user-images.githubusercontent.com/209434/86450923-823c2300-bd1a-11ea-852b-da7c74f403bd.png">

Still obvious that you can "run" the code, but IMO less obtrusive to the user.

**Comment by dbitouze** [comment]
> copying can be done with the keyboard

And the mouse. I'm in favor of the "copy" button: that's something which is missing e.g. in SE: selecting the code with the mouse is sometimes painful, especially when the code is long enough to not being entirely displayed.

Otherwise, I second the suggestion about the "edit" button.

**Comment by josephwright** [comment]
This really is one for Jonas, as it's about design/user access.

**Comment by pgundlach** [comment]
(@jonasjacek  feel free to just close this issue, I don't think it needs to stay around as open)

**Comment by josephwright** [comment]
@pgundlach It's an important question, so I think we keep the issue open until @jonasjacek has made some mock-ups: probably we need to see how different interfaces 'feel'.

**Comment by davidcarlisle** [comment]
@pgundlach yes I wondered about this. As Joseph said Jonas will probably want to move things around anyway, but I'll mention a couple technical things that lead to the current interface.

The copy button is mostly a convenience to avoid having to select large blocks with a mouse, but it also places the plain text on the clipboard with all syntax highlighting stripped. If you copy the formatted version what you get when you paste depends on the receiving client.

The edit button is similar, with the syntax highlighting being used (the default one on github pages) if you simply enable the `<pre>` element to be conteteditable=true then most editing works but you can not add a newline as every line is in a formatted span and the return key is disabled (at least in some browsers). So when you click on edit, the content is replaced by its text content and you lose all syntax highlighting  but you can add newlines as expected.

So (with the current systems) having edit always on would mean no syntax highlighting on the site.
