### ISSUE TITLE
Detect when to use PDF.js

### ISSUE THREAD

**Issue by joulev** [learnlatex/learnlatex.github.io#56]
The help page says (emphasis is mine)

> The LaTeX CGI service [...] makes use of PDF.js to enable display of PDF on mobile and other browsers **without built in PDF readers**.

I am using Brave browser in Windows 10, and it does have a PDF reader built-in (which is, I think, the same reader used in Chrome and other Chromium browsers). But PDF.js is still used. And in my opinion, the default reader looks nicer. Screenshots of the output of the first example in [lesson-04](https://www.learnlatex.org/en/lesson-04) at zoom 300%, the above is from PDF.js, the below is from the default reader:

![image](https://user-images.githubusercontent.com/44609036/86565715-938f6480-bf92-11ea-82d5-acab3e4961fd.png)

![image](https://user-images.githubusercontent.com/44609036/86565727-9b4f0900-bf92-11ea-8382-bdd2614b1f6a.png)

I know PDF.js is important because not every browser has a PDF reader; however some do have. The site should only use PDF.js when it has to.

**Comment by davidcarlisle** [comment]
I have some sympathy with that but as far as I know I have no way of telling. 
My (rough, unimplemented) plan is that at the ;atexcgi.xyz end I add a parameter to the post form to choose between using pdf.js or not (that will be trivial as the change to use pdf.js was a one line change).

Then at the learnlatex.org side initially allow that parameter to be set something like 

`% !TEX (viewer=) PDF.js`

or

`% !TEX (viewer=) PDF.browser`

Then perhaps (if we decide to allow cookies) the user would be able to set a site default to save having to edit each example to add !TEX comment each time.

There could be other similar choices such as using latexcgi.xyz or using the original latexonline.cc server etc.

**Comment by davidcarlisle** [comment]
I implemented the above, currently only documented at latexcgi, not here

https://davidcarlisle.github.io/latexcgi/#form-fields

so you can use `!TEX pdf`  to get your browser rendering, or `%!TEX log` to just get the log file and no pdf. The default remaining `!TEX pdfjs`

I think this is as much as I can do unless we decide to implement user defaults. If a user preference for `%!TEX pdf` were in a cookie it would be trivial to add that to each example (or not add it explicitly but make it the default, whichever seems the most reasonable behaviour?)

But using or not using user defaults is a general issue we need to decide.

This has only been live for a few minutes, so if you want to test it, I'd be interested to know if it works:-)

**Comment by joulev** [comment]
@davidcarlisle Just tested it, and it looks great!

Maybe we should introduce some "Settings" page, where things like this can be customized so that the user doesn't need to manually add `% !TEX pdf` or `% !TEX log` to every code block. (If there is a Settings page, far more things can be customized, like the syntax highlighting theme, dark/light mode, etc. so I think it should be implemented at some point in the future.)

**Comment by davidcarlisle** [comment]
closing this now as I opened #58 on the issue of user defaults in general.
