### ISSUE TITLE
Links of Translation file are not working

### ISSUE THREAD

**Issue by EmanuelPrima** [learnlatex/learnlatex.github.io#68]
The last 2 links of ["Translating examples" of the `TRANSLATIONS.md` file](https://github.com/learnlatex/learnlatex.github.io/blob/master/TRANSLATIONS.md#translating-examples) are not working.

**Comment by davidcarlisle** [comment]
Hi you are looking at the source file and the file names (in particular dropped extensions) are different there, the links should work if you view

https://www.learnlatex.org/TRANSLATIONS

**Comment by davidcarlisle** [comment]
although For some reason I used local links for them but a full https://www.learnlatex.org link for others eg the Japanese example, I can use the absolute URL for all of them so they work from anywhere.
