### ISSUE TITLE
Include discussion of the formatting of the differential operator

### ISSUE THREAD

**Issue by josephwright** [learnlatex/learnlatex.github.io#70]
The formatting of the differential operator ('d'/`_d_') can be somewhat controversial, and certainly varies between different traditions. We could handle this in two ways

- Avoid it entirely by not including any examples
- Mention in some neutral way that authors need to be aware of this

The latter seems best: perhaps a short section in lesson 10?  For example
>
> ## Formatting of the differential operator
>
> The use of italic for variables and upright font for operators is seen in most cases, for example '_x_' (`$x$`) versus 'sin' > (`$\sin$`). The differential operator ('d'/'_d_') is a more complicated case. In the (pure) mathematics tradition, it is 
>  typeset in italics, so for example '_dx_'. In contrast, in engineering, it is typically given upright, 'd_x_' 
> (`$\mathrm{d}x$`), which follows an ISO. Here, we cannot recommend one over the other, but can advise that you 
> check the expectation in your area when writing your documents.

**Comment by marmotghost** [comment]
Thanks for the issue! Just for the records, I do not believe that there is a clear preference for italic differential `d`'s in pure math. For instance, on p. 32 of the [AMS guide](https://www.ams.org/publications/authors/AMS-StyleGuide-online.pdf)  they are upright (but you can find also italic versions in this style guide), and in [these math lectures](https://web.ma.utexas.edu/users/a.debray/lecture_notes/) the differential `d` is consistently upright. However, I absolutely support the proposal to leave the topic out of a guide for newcomers, just wanted to say that the notion "pure maths uses italic differential d's" is not a correct description.

**Comment by car222222** [comment]
There are, of course, a host of similar details, nuances and varied practices throughout math typesetting.  These are also time-dependent!

**Comment by josephwright** [comment]
> There are, of course, a host of similar details, nuances and varied practices throughout math typesetting. These are also time-dependent!

Yes but this is by far the most ... tricky ... one.

**Comment by marmotghost** [comment]
It isn't too tricky in my humble opinion. There are [official conventions](http://www.tug.org/TUGboat/Articles/tb18-1/tb54becc.pdf). Of course, nobody should be forced to follow these, or any conventions. However, one should certainly be *very* careful when promoting certain practices. It has been suggested that the differential d is not an operator (not true) or that the tradition to typeset differential d's italic goes back to Gauss and Euler (not true, their publisher typeset it in the same font as e.g. the trigonometric functions, so if you really want to follow the practices of Gauss and Euler's publishers, you should type differential d's upright as long as you use `\sin` to typeset a sine function). To be clear, I do not want to force others to use my conventions, but want to avoid that nonstandard conventions get displayed on a site from which users are supposed to learn LaTeX. One of the reasons is that I would have benefitted a lot if I was informed about these pitfalls before I created my first few official documents, until I realized that denoting the time derivative of a distance `$d$` by `$\frac{dd}{dt}$`, say, is a really bad idea. We should spare newcomers to LaTeX from having to go though this.

**Comment by car222222** [comment]
@marmotghost There are official conventions, but they are never used by any math publishers (not in the UK or USA and many other locales, at least).  Or by most communities of math authors.

**Comment by car222222** [comment]
It is impossible to enforce any abstract (unenforceable and largely unheeded) standards on this material (or on any useful teaching material).  

If you want a site to teach 'mathematical typesetting' (possibly including useless abstract standards for it:-) then that would be a separate enterprise. 

Here we 'teach them the tools', rather than educate them in typography and standards.

**Comment by car222222** [comment]
p
@marmotghost  wrote:
> denoting the time derivative of a distance $d$ by $\frac{dd}{dt}$, say, is a really bad idea. 

Yes, it probably is, but understanding the reasons for this is not really part of 'learning latex', at least not at this elementary stage.  Note that similar considerations apply to 'learning tex math' or 'learning mathml'.  All good stuff but for a different place (possibly linked in some sense to this site and many others that are specifically about math encodings.

> We should spare newcomers to LaTeX from having to go though this.

Probably impossible.  As above, what you missed out on was learning about the importance and utility of 'abstraction in the encoding of math', a vast subject that is relevant to many systems but not obviously a part of basic instruction in latex.

Some detailed notes, from my experience: 
1.  A good abstraction for this particular case would not have any 'differential d' at all: something more like 
  `$\diffwrt{d}{t}$`
or an even more semantic representation such as
   `$\diffwrt{\depvar{distance}}{\deovar{time}}$`
(I was brought up to teach calculus without any 'differentials', 'fluxions', 'fractions' etc, only 'functions, 'derivative functions' and 'anti-derivative functions' !!)
2.  I have no idea whether this is codified in any standards, but it is very well-known 'within the (Anglo-Saxon??) craft/trade' that (in calculus at least) using 'd' as a variable identifier for anything is a 'really bad idea'.  Distance is, in the 'universal de facto standard (??)' always denoted by 's'.

**Comment by car222222** [comment]
Or maybe a more general site on 'Using LaTeX to write conformant documents' so that we can keep this one reasonably free of 'official conventions' and arbitrary abstract, unused standards.

**Comment by car222222** [comment]
Or maybe a subject area on 'Using LaTeX for engineering standards compliance', well-separated from teaching 'math in LaTeX'.

**Comment by marmotghost** [comment]
Many mathematicians do typeset the differential d upright. See e.g. https://web.ma.utexas.edu/users/a.debray/lecture_notes/ and many many math papers. I would really like to understand where the narrative that mathematicians typeset the differential d italic comes from. It is certainly not true. What is true is that almost all mathematicians typeset the differential d upright. (Here I have used "almost all" in the sense of "all but finitely many exceptions". ;-) And apart from that, the LaTeX users do not just consist of mathematicians and engineers, there are also physicists etc.

**Comment by car222222** [comment]
But this random paper uses non-italic for the variable also, as in the differential/derivative form ‘dR’. 

https://web.ma.utexas.edu/users/a.debray/lecture_notes/s17_geometric_Langlands.pdf

I bet I could find any number of different typographical conventions in such a large collecation of mathematical works! 

“There are more things in Heaven and Earth, Horatio, than are dreamt of in your typography.”

**Comment by marmotghost** [comment]
As you say, you will find any convention. But to it does not seem appropriate to push a particular one for the differential d, the more so in other occasions learnlatex aims at avoiding analogous problems: https://github.com/learnlatex/learnlatex.github.io/issues/112. For instance, physicists write `\int\diff x\,f(x)` instead of `\int f(x)\diff x`, and I would not want to see this choice promoted either. But, as far as I am concerned, as long learnlatex decides to hurt my eyes, I will certainly not recommend it to anyone.

**Comment by josephwright** [comment]
@marmotghost  I'm happy to adjust the text, but one issue for me at least is that the amount of math mode we can cover is actually very small. There are users who need lots of maths, and ones for whom it's a complete turn-off. (I have wondered about a series of math mode-specific lessons.)

Would something like

> Note that formatting of the differential operator varies: some publishers use 'd' whilst others use '_d_'. One way to write your source to allow you to handle either is to create a command `\diff` that you can adjust as required.

work for you?

**Comment by marmotghost** [comment]
@josephwright Thanks! The text you suggest is great! (Although some versions of `\diff` also promise to give the right spacing, but these are details.) I'd also suggest to reword the statement on the purpose of the `\,` because it can lead to misinterpretations. 

I think that some discussion on the notation can be useful, but easily can become excessive. There already exist resources like the AMS style guide (in which you can find both upright and italic differential d's), and there is no "one size fits all". So IMHO the best thing would be to disentangle all these detailed questions from a site that aims at making LaTeX more accessible to the community. Perhaps one could add some links to some standard style guides such as the one by AMS.

**Comment by josephwright** [comment]
I've added some text: the lesson is already pretty long, and I'm wary of going further.
