### ISSUE TITLE
Provide a search bar

### ISSUE THREAD

**Issue by stone-zeng** [learnlatex/learnlatex.github.io#80]
It will be helpful to have the function for searching in the website, for example when one wants to find the usage of some commands, etc.

**Comment by josephwright** [comment]
Part of the design aspect, so one for Jonas.

**Comment by jonasjacek** [comment]
I was wrapping my head around this for some time. The search I used for latex-project.org is from Google ([Google Custom Search](https://cse.google.com/)). Is it ok to use it for learnlatex.org, too?

**Comment by davidcarlisle** [comment]
@jonasjacek  yes I think a google custom site search should be enough, (that's also what we have at texfaq.org)

**Comment by dbitouze** [comment]
There are folks who don't want to rely on Google and who use e.g. DuckDuckGo to search on the Web. They probably would be reluctant to search on learnlatex if the only way would be via Google.

**Comment by jonasjacek** [comment]
DuckDuck has a [similar service](https://duckduckgo.com/search_box) to Google.

There is also an option to use a service like [Algolia](https://www.algolia.com/). Implementation is a lot more work though. It's on the other end of the spectrum, compared to Google/DuckDuck.

**Comment by stone-zeng** [comment]
Note that in china mainland google and duckduck are not available, unfortunately.

**Comment by jonasjacek** [comment]
> Note that in china mainland google and duckduck are not available, unfortunately.

Does Baidu offer a similar service?

**Comment by stone-zeng** [comment]
> Does Baidu offer a similar service?

I think bing is ok.

**Comment by dbitouze** [comment]
> I think bing is ok.

@stone-zeng Well, I guess Bing (Microsoft) would not be better received than Google.

**Comment by jonasjacek** [comment]
At least [Bing Custom search](https://www.customsearch.ai/) is supposedly ad free.

**Comment by jonasjacek** [comment]
# Update

## DuckDuckgo
I've chosen DuckDuck for now as they allow to disable ads, customize the result page via simple URL parameters, and do not require account creation. Also, privacy of users will profit. Love it. **Important:** As of now looks up results for latex-project.org, as learnlatex.org is (purposely) blocking search engine crawlers via robots.txt, which means we will not see any results for now. This will be changed later.

---

## Google
Although I've tried to create a Google custom search engine (CSE). Unfortunately, I did not receive any emails from them to confirm my account creation. :-1:  Also, contains ads.

## Bing
Second choice, also requires account creation. Contains ads.

## Baidu
Requires account creation with a Chinese mobile phone number. I am blocked. If anyone wants to help, ping me. Probably contains ads.

---

## Summary

Right now, I am happy with DuckDuckGo, although contrasts could be better for some search result page (SERP) elements, which I am not able to style via parameters. I am considering contacting them about that. 

Search box design work has not started yet, only the result page design has been worked on. My focus was branding (colors) and on accessibility (contrasts, font sizes, etc.)

**Comment by jonasjacek** [comment]
@josephwright & @davidcarlisle, could please contact Algolia and ask if we can use Algolia for free? There is an application form on [this page](https://www.algolia.com/for-open-source/) (we may need to create an account first). This would solve the challenges we see in offering search for e.g. China.

**Comment by josephwright** [comment]
I guess I need to ask for a free trial?

**Comment by jonasjacek** [comment]
Yes. Would be great if you could do it.

**Comment by josephwright** [comment]
Looking at Algolia, it's not actually free if you get to a reasonable number of hits. From the above, Bing is and works everywhere: seems the easiest solution.

**Comment by FrankMittelbach** [comment]
> Note that in china mainland google and duckduck are not available, unfortunately.

@stone-zeng I'm not sure I understand. Does this mean that the search box on https://www.latex-project.org doesn't work for you or  only that google.com and the like do not work for you?

**Comment by jonasjacek** [comment]
> Looking at Algolia, it's not actually free if you get to a reasonable number of hits. 

Oh. I didn't see that. "The AOS plan is based on Algolia's paid Starter Plan. The standard volume of the AOS Plan is 100k records and 200k operations monthly - a $70/month value." Darn.

> From the above, Bing is and works everywhere: seems the easiest solution.

I will check it out today.

**Comment by dbitouze** [comment]
> > > From the above, Bing is and works everywhere: seems the easiest solution.
> 
> not really a fan of bing but that is my bias I guess.

Me neither, as I said [here](https://github.com/learnlatex/learnlatex.github.io/issues/80#issuecomment-743127858).

What about integrated search engine, as in [Sphinx-doc](https://www.sphinx-doc.org/en/master/index.html)?

**Comment by josephwright** [comment]
@dbitouze But that site is controlled by people who do 'real' programming in a way that suggests they might actually be in a position to write the back-end: that's not us (at least with learnlatex.org hats on)

**Comment by FrankMittelbach** [comment]
I'm for keeping it simple and that means in my opinion google duckduckgo or maybe bing.

**Comment by jonasjacek** [comment]
So far I have added only duckduckgo. Is there a need to add another search engine, for example for a specific country? Are you happy with the results (needs full (translated) meta data on all pages to work)?

So, is this topic still open?

**Comment by josephwright** [comment]
This is sorted: I am closing
