### ISSUE TITLE
Provide a more friendly way to switch languages

### ISSUE THREAD

**Issue by stone-zeng** [learnlatex/learnlatex.github.io#81]
Currently the website use a simple dropdown menu with only language tags to switch, like:

<img width="171" alt="Screen Shot 2020-08-04 at 19 21 07" src="https://user-images.githubusercontent.com/18233088/89288091-a7a8ad80-d687-11ea-9b3c-d347c9047ca8.png">

A  more friendly way, e.g. use a localized name, may help people choose the one they need.

For example, <https://docs.github.com/> use a localized name + English full name:

<img width="287" alt="Screen Shot 2020-08-04 at 19 24 14" src="https://user-images.githubusercontent.com/18233088/89288365-17b73380-d688-11ea-88ce-e898473f066f.png">

**Comment by josephwright** [comment]
One for Jonas: I think the approach is well-established, it's just that we've not yet got to that stage.

**Comment by jonasjacek** [comment]
Still not looking great, but functionality is done. Preview: https://learnlatex.netlify.app/

https://github.com/learnlatex/learnlatex.github.io/commit/e5da1f7ec8ec6a2088e2c20295db14fe5176640c and
https://github.com/learnlatex/learnlatex.github.io/commit/aac62a5a0ca92c4f0a27b94c18085d3bec76dd3e

**Comment by joulev** [comment]
@jonasjacek It is not yet really responsive I think.

![0D900FCB-4CCB-4635-B2E3-44F56F8AD6F1](https://user-images.githubusercontent.com/44609036/93412898-47349f00-f8c8-11ea-94e4-7e7bd50bead2.jpeg)

**Comment by jonasjacek** [comment]
Thank you for your feedback. I am aware of this.

I follow the _form follows function_ paradigm for web design. So, I have not yet worked on the (responsive) design but on functionalities in regards to accessibility, internationalization, etc.

I'll keep the ticket closed, as I still have not decided, where the language switch actually will appear and how it will look like.
