### ISSUE TITLE
Titles of pages

### ISSUE THREAD

**Issue by joulev** [learnlatex/learnlatex.github.io#84]
Currently all pages don't have titles.

![image](https://user-images.githubusercontent.com/44609036/89797183-d1187c00-db54-11ea-8383-9897c542c876.png)

Maybe there are some regressions? Although I am not sure, I really think the titles used to work some time ago.

[Firefox 79, Windows 10]

**Comment by davidcarlisle** [comment]
Ah good catch: this used to be added by the Jekyll `seo` plugin  which adds several lines but as @jonasjacek pointed out several are less than helpful.  I could add (just) `<title>` back for now pending the main site restyling, unless that would cause Jonas complications?
