### ISSUE TITLE
Unclear wording in more-10.md

### ISSUE THREAD

**Issue by jejust** [learnlatex/learnlatex.github.io#87]
Hi all,
In the file "more-10.md", I have difficulties understanding (and translating) this paragraph:
```
In addition there are variants of the display environments ending
in `ed` that make a subterm of a larger display for example, `aligned` and
`gathered`.
```

The part `a subterm of a larger display` doesn't sound really explicit to me. Is it easy to understand for a native English speaker? (if so, I'll use the example to work out a translation)

Thanks!

**Comment by joulev** [comment]
"Subterm" here is like a part of a normal display equation but that part itself looks like a display equation of its own.

In other words, you can "add" an `align` inside a normal equation using `aligned`.

```tex
\documentclass{article}
\usepackage{amsmath}
\begin{document}
``A display equation of its own''
\begin{align*}
1 + 2 &= 3\\
4 + 5 &= 6
\end{align*}

``A part of a normal display equation''
\[\left[\begin{aligned}
1 + 2 &= 3\\
4 + 5 &= 6
\end{aligned}\right]\]
\end{document}
```

![image](https://user-images.githubusercontent.com/44609036/90250914-14316280-de67-11ea-8419-b9fc23faa701.png)

**Comment by davidcarlisle** [comment]
As @joulev says it's trying to say whether the environment is a whole display or part of a larger display.  `align` is like `equation` and makes a whole display. `aligned` is like `array` and makes a part of a display s has to be used inside another environment that starts the math mode.

the sentence would possibly be clearer if written as two sentences?

```
In addition there are variants of the display environments ending
in `ed` that make a subterm of a larger display.
For example, `aligned` and `gathered` are variants of `align` and `gather` respectively.
```

**Comment by jejust** [comment]
With `inside`, that already clearer, thanks!
If I translate back my translation, I have:

```
In addition, there are variants of the display environments ending in `ed` that
allow to build a sub-formula meant to be included inside a larger formula.
For example, `aligned` and `gathered` are variants of `align` and `gather`,
respectively.
```
