### ISSUE TITLE
Example for the `standalone` class (file `more-05.md`) doesn't compile with _LaTeX Online_

### ISSUE THREAD

**Issue by jejust** [learnlatex/learnlatex.github.io#89]
In `more-05.md`, if I try to compile the example presenting the `standalone` class 
```latex
\documentclass{standalone}
\usepackage[T1]{fontenc}
\begin{document}
A simple document: this will be a very small box!
\end{document}
```

with the _LaTeX Online_ button, I get this error message:
```
Bad Input

Timeout/Error status: 1
```

while it works smoothly when I compile it locally on my computer (TeXlive 2020).
(I haven't tried with Overleaf)

**Comment by davidcarlisle** [comment]
thanks, I can confirm, give me a minute I'll see what it is doing....

**Comment by davidcarlisle** [comment]
oh standalone tries to input `/dev/null` and /dev isn't in the white list of allowed places to input.  I'll fix

**Comment by davidcarlisle** [comment]
Thanks checked it in English and French, works now.
